### ISSUE TITLE
How to retrieve the anime ratings with the API?

### ISSUE THREAD

**Issue by Emasoft** [sprak3000/AnimeNewsNetworkDataAPI#3]
Hi! 
I need to retrieve the rating (and maybe the number of voters) of an anime entry from the AnimeNewsNetwork Encyclopedia. But I cannot find the documentation on how to do that with the API. 
I'm writing an addon for a certain popular media center that displays the rating of each anime from ANN. Currently it takes the rating score from IMDB like it does for movies, but for anime IMDB ratings are totally unreliable. For anime the ANN ratings are the most trustworthy on the web (thanks to the voters, a great community of historical users!), but I cannot find a way to query those from the ANN Encyclopedia API. 

Can anybody help me with that? thanks.

**Comment by sprak3000** [comment]
My pull requests for guzzle-services were finally merged in. Have updated to use it in turn requiring an update to Guzzle 5.0. In turn, required overhauling how the tests work and finding out that you no longer need to call `toArray()` on the result from the API.

Ratings data now coming through the API.
